### ISSUE TITLE
how to generate psm header file and errors occur with graph construction

### ISSUE THREAD

**Issue by irleader** [AmadeusloveIris/GraphNovo#2]
In graph construction, <psm header name without 'csv'>,  how to generate a psm header file from any original .mgf file?

When I do graph construction with the supplied "A_Thaliana.csv" and "A_Thaliana.mgf" under the same folder, there is error:

 File "D:\GraphNovo\genova\utils\graph_constructor.py", line 332, in <module>
    product_ion_info = all_spectra[spec_index]
KeyError: 'A_Thaliana:F2.2:97749'

When I do graph construction with the supplied "C_Elegans.csv" and "C_Elegans.mgf" as well as "E_Coli.csv" and "E_Coli.mgf", there is another error:

Traceback (most recent call last):
  File "D:\GraphNovo\genova\utils\graph_constructor.py", line 335, in <module>
    node_mass, node_input, rel_input, edge_input, graph_label = graph_gen(seq, product_ions_moverz, product_ions_intensity, precursor_ion_mass, precursor_charge>2)
  File "D:\GraphNovo\genova\utils\graph_constructor.py", line 152, in __call__
    subedge_maxnum, edge_type, edge_error = self.edge_generator(node_mass,precursor_ion_mass)
  File "D:\GraphNovo\genova\utils\graph_constructor.py", line 271, in edge_generator
    edge_type, edge_error = edge_matrix_generator(n,
  File "edge_matrix_gen.pyx", line 13, in edge_matrix_gen.edge_matrix_generator
    long[:,::1] start_edge_type,
ValueError: Buffer dtype mismatch, expected 'long' but got 'long long'

**Comment by SamvPy** [comment]
Hi,

Were you able to fix this already? I am lost how the required psm header file should be generated from an MGF.

Thanks in advance!

-Sam

**Comment by codjjj** [comment]
Hi,
I'm also wandering how I can convert the initial (csv,mgf) file to construct the  graph  ?
README said `cd genova/utils
sh parrllel_preprocessing.sh <total_threads> <data_path> <psm header name without 'csv'>`
but where is the parrllel_preprocessing.sh?
Thansk in advance!

**Comment by devansh-shah56** [comment]
Hi,
Has anyone figured out a way to make the PSM csv file, or is there a pipeline that exists which I could use? I did use the a parsing script but when I run the `parallel_preprocessing.sh` file, it always runs into some indexing error or dtype error (~line 300 in `graph_constructor.py`). It would be great if someone could help out!
Thanks!
